apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-service
spec:
  replicas: 3 # Numero di repliche desiderate
  selector:
    matchLabels:
      app: home-service
  template:
    metadata:
      labels:
        app: home-service
    spec:
      containers:
        - name: home-service
          image: psanger/home-service:latest
          ports:
            - containerPort: 8082