version: "3.8"
services:
  api-gateway:
#    build: C:\Users\miky9\IdeaProjects\spikes\MusicDraftBackend\api-gateway
    image: psanger/api-gateway:latest
#    image: ziomike97/api-gateway:latest
    restart: always
    ports:
      - 9095:9095
    networks:
      - opnet


#  musicdraft-frontend:
##    image: musicdraft-app:v1
#    build: C:\Users\miky9\OneDrive\Desktop\Progetti Angular\frontend
##    command: npm start
##    restart: always
#    ports:
#      - 4200:80
#    networks:
#      - opnet


  matchmaking-service:
    image: psanger/matchmaking-service:latest
#    image: ziomike97/matchmaking-service:latest
    restart: always
    ports:
      - 8083:8083
    depends_on:
      - mysqldb
      - rabbitmq
    networks:
      - opnet

  authentication-service:
    build: C:\Users\miky9\IdeaProjects\spikes\MusicDraftBackend\authentication-service
#    image: psanger/authentication:latest
#    image: ziomike97/authentication-service:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - authdb
      - rabbitmq
    networks:
      - opnet

  home-service:
    image: psanger/home-service
#    image: ziomike97/home-service
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
      - authentication-service
      - rabbitmq
    networks:
      - opnet

  collectdata-service:
#    image: collectdata-service-server:latest
    image: psanger/collectdata-service
#    image: ziomike97/collectdata-service
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
    networks:
      - opnet

  marketplace-service:
    image: psanger/marketplace-service
#    image: ziomike97/marketplace-service
    restart: always
    ports:
      - 9091:9091
    depends_on:
      - mysqldb
    networks:
      - opnet

  carte-e-mazzi-service:
#    build: C:\Users\miky9\IdeaProjects\spikes\MusicDraftBackend\carte_e_mazzi-service
    image: psanger/carte-e-mazzi-service
#    image: ziomike97/carte-e-mazzi-service
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - mysqldb
      - rabbitmq
    networks:
      - opnet

  authdb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: db_authentication
      MYSQL_USER: authentication
      MYSQL_PASSWORD: authentication
      MYSQL_ROOT_PASSWORD: authentication
    networks:
      - opnet

  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: db_musicdraft
      MYSQL_USER: musicdraft
      MYSQL_PASSWORD: musicdraft
      MYSQL_ROOT_PASSWORD: musicdraft
    networks:
      - opnet


  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672" #JMS Port
      - "15672:15672" #Management Port - default user:pass = guest:guest
    networks:
      - opnet


networks:
  opnet:
    driver: bridge