version: "3.8"
services:
  api-gateway:
    image: psanger/api-gateway:latest
    restart: always
    ports:
      - 9095:9095
    networks:
      - opnet

#  musicdraft-frontend:
#    image: psanger/musicdraft-frontend:latest
#    restart: always
#    ports:
#      - 4200:4200
#    depends_on:
#      - api-gateway
#      - marketplace-service
#      - matchmaking-service
#      - carte-e-mazzi-service
#      - home-service
#      - authentication-service
#      - collectdata-service

    networks:
      - opnet

  matchmaking-service:
    image: psanger/matchmaking-service:latest
    restart: always
    ports:
      - 8083:8083
    depends_on:
      - mysqldb
      - rabbitmq
    networks:
      - opnet
  authentication-service:
#    image: authentication-service-server:latest
    image: psanger/authentication-service:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysqldb
      - rabbitmq
    networks:
      - opnet

  home-service:
    image: psanger/home-service:latest
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
      - authentication-service
      - rabbitmq
    networks:
      - opnet

  collectdata-service:
#    image: collectdata-service-server:latest
    image: psanger/collectdata-service:latest
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
    networks:
      - opnet

  marketplace-service:
    image: psanger/marketplace-service:latest
    restart: always
    ports:
      - 9091:9091
    depends_on:
      - mysqldb
    networks:
      - opnet

  carte-e-mazzi-service:
      image: psanger/carte-e-mazzi-service:latest
      restart: always
      ports:
        - 9092:9092
      depends_on:
        - mysqldb
        - rabbitmq
      networks:
        - opnet


  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: db_musicdraft
      MYSQL_USER: musicdraft
      MYSQL_PASSWORD: musicdraft
      MYSQL_ROOT_PASSWORD: musicdraft
    networks:
      - opnet


  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672" #JMS Port
      - "15672:15672" #Management Port - default user:pass = guest:guest
    networks:
      - opnet


networks:
  opnet:
    driver: bridge