version: "3.8"
services:
  authentication-service:
#    image: authentication-service-server:latest
    build: C:\Users\pietr\Desktop\Uni\TAAS\Spike\MusicDraft-Backend\authentication-service
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysqldb
    networks:
      - opnet

  home-service:
    build: C:\Users\pietr\Desktop\Uni\TAAS\Spike\MusicDraft-Backend\home-service
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
      - authentication-service
    networks:
      - opnet

  collectdata-service:
#    image: collectdata-service-server:latest
    build: C:\Users\pietr\Desktop\Uni\TAAS\Spike\MusicDraft-Backend\collectdata-service
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
    networks:
      - opnet
  marketplace-service:
    build: C:\Users\pietr\Desktop\Uni\TAAS\Spike\MusicDraft-Backend\marketplace-service
    restart: always
    ports:
      - 9091:9091
    depends_on:
      - mysqldb
    networks:
      - opnet
  carte_e_mazzi-service:
      build: C:\Users\pietr\Desktop\Uni\TAAS\Spike\MusicDraft-Backend\carte_e_mazzi
      restart: always
      ports:
        - 9092:9092
      depends_on:
        - mysqldb
      networks:
        - opnet


  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: db_musicdraft
      MYSQL_USER: musicdraft
      MYSQL_PASSWORD: musicdraft
      MYSQL_ROOT_PASSWORD: musicdraft
    networks:
      - opnet

networks:
  opnet:
    driver: bridge