version: "3.8"
services:
  server:
    build: ../..
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: spotifydb
      MYSQL_USER: piero
      MYSQL_PASSWORD: piero1234+
      MYSQL_ROOT_PASSWORD: piero1234+