version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysqldb


  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: db_musicdraft
      MYSQL_USER: musicdraft
      MYSQL_PASSWORD: musicdraft
      MYSQL_ROOT_PASSWORD: musicdraft

#  mysqldb:
#    image: "mysql:5.7"
#    restart: always
#    ports:
#      - 3307:3306
#    environment:
#      MYSQL_DATABASE: db_utenti
#      MYSQL_USER: michele
#      MYSQL_PASSWORD: michelem
#      MYSQL_ROOT_PASSWORD: michelem