apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking-service
spec:
  replicas: 3 # Numero di repliche desiderate
  selector:
    matchLabels:
      app: matchmaking-service
  template:
    metadata:
      labels:
        app: matchmaking-service
    spec:
      containers:
        - name: matchmaking-service
          image: psanger/matchmaking-service:latest # Sostituisci con il tuo percorso completo dell'immagine Docker
          ports:
            - containerPort: 8083